version: 2

jobs:
  build:
    working_directory: /pedantic
    docker:
      - image: python:3.6-alpine
    steps:
      - checkout
      - run: apk add --update curl nodejs yarn bash
      - run: pip install -r requirements.txt
      - run: yarn
      - run: bin/test
      - run:
          command: bin/smoke_test
          environment:
            PORT: 5000
      - run: pip install codecov
      - run: codecov
